# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  newman: postman/newman@0.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  run-collection:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/14272639-db7a0eb9-02aa-4af3-94e0-f5b83f361d2e?apikey={{api_key}}

workflows:
  example-workflow:
    jobs:
      - run-collection
