# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  newman: postman/newman@0.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  run-collection:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://devrel.postman.co/workspace/CircleCI-Practice-Workspace~003c4a7e-859b-4339-97e4-c02207085994/collection/14272639-db7a0eb9-02aa-4af3-94e0-f5b83f361d2e?apikey=PMAK-61683d1b5669aa0046011479-960ef5f1a6018fae39884e5cc4a86c1f9b

workflows:
  example-workflow:
    jobs:
      - run-collection